// Canonical undo-log kind list (S3.3 / K9).
//
// Every kind that Rust can write to the undo log (via `undo::log_entry` and
// kind-passing helpers like shell's `apply_advanced_dword`, plus the kinds
// referenced in undo.rs's revert arms). This is the source of truth the
// frontend checks against:
//   - KindChip must style every kind here (KIND_CHIP_STYLES == this set)
//   - `scripts/check-kind-parity.mjs` re-extracts the Rust side and fails on
//     drift, so a new `log_entry("kind", …)` can't ship without a chip style.
//
// Generated Aug 13 2026 from the Rust sources — keep in sync via the script.
export const UNDO_KINDS: readonly string[] = [
  "accent",
  "accessibility",
  "animated_wallpaper",
  "animated_wallpaper_stop",
  "archive",
  "asr_rule",
  "blue_light",
  "browser_policy",
  "cfa",
  "cursors",
  "custom_scene_deleted",
  "custom_scene_saved",
  "definitions_update",
  "display_profile",
  "downloads_expired",
  "duplicates_removed",
  "file_association",
  "focus_mode",
  "font_install",
  "font_substitution",
  "font_uninstall",
  "focus_session",
  "game_mode",
  "game_profile",
  "junk_clean",
  "lock_screen",
  "macro",
  "macro_fired",
  "marketplace_apply",
  "mode",
  "network_reset",
  "permission",
  "power",
  "power_plan",
  "process_ended",
  "registry_cleanup",
  "rename",
  "rgb_color",
  "rt_disable",
  "rt_reenable",
  "scan",
  "scheduled_maintenance",
  "shell_restart",
  "snapshot",
  "sort",
  "sound_event",
  "sound_scheme",
  "startup_disable",
  "startup_folder_disable",
  "storage_clean",
  "stream_layout",
  "style_applied",
  "taskbar_alignment",
  "taskbar_autohide",
  "taskbar_color_match",
  "taskbar_position",
  "taskbar_size",
  "threat_remove",
  "threat_restore",
  "transparency",
  "trash_emptied",
  "uninstall",
  "video_wallpaper",
  "video_wallpaper_stop",
  "vpn_connect",
  "vpn_disconnect",
  "wallpaper",
  "wallpaper_slideshow",
  "widget_layout",
  "wifi_forgot",
];

export const UNDO_KIND_SET: ReadonlySet<string> = new Set(UNDO_KINDS);
