name: Feature request
description: Suggest an idea for Reforge
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What are you trying to do that Reforge doesn't support yet?
      placeholder: "I want to be able to ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you imagine it working?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Anything else you've tried or thought of?
