// Flagship catalog (A1.2). Hand-designed styles grounded in the wallpaper
// library — every accent is derived from the wallpaper's real extracted
// palette (dominant or secondary), every config is a deliberate choice, and
// the copy names the look honestly. 72 flagships: the original 35 plus a
// category × mood coverage pass and six curated era/collection sets.
//
// `collection` groups flagships into eras (Studio, Nordic, Neon '80s, Dark
// Forest, Ocean, Midnight) so the studio can browse them as sets.

import type { StyleDef } from "./types";

export const HERO_STYLES: StyleDef[] = [
  // ---- animated scenes -----------------------------------------------------
  {
    id: "midnight-rain", name: "Midnight Rain",
    tagline: "Indigo calm over a slow aurora",
    description: "A drifting aurora scene, deep-indigo accent, translucent taskbar. Quiet enough to think in, pretty enough to leave on.",
    category: "Calm", mood: "calm", mode: "dark", accent_hex: "#6D7CFF",
    gradient: ["#0B1026", "#2A3B7C"], wallpaper: { type: "scene", sceneId: "aurora-drift" },
    sceneTweak: { speed: 0.5, density: 0.8 }, transparency: true,
    taskbar: { size: "medium", alignment: "center", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["calm", "indigo", "dark", "premium", "scene"],
    quiz: { dark: 3, cool: 2, calm: 3, minimal: 1 },
    tier: "flagship", collection: "Midnight",
  },
  {
    id: "sunset-boulevard", name: "Sunset Boulevard",
    tagline: "Tangerine dusk over a retro grid",
    description: "A retro-sunset scene, warm tangerine accent, centered taskbar. Energetic at the edges, cozy in the middle.",
    category: "Energetic", mood: "energetic", mode: "dark", accent_hex: "#FF7B54",
    gradient: ["#1A0E2E", "#E4572E"], wallpaper: { type: "scene", sceneId: "retro-sunset" },
    sceneTweak: { speed: 1.0, density: 1.0 }, transparency: true,
    taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "todo"],
    tags: ["warm", "retro", "energetic", "dusk", "scene"],
    quiz: { dark: 2, warm: 3, energetic: 2, retro: 2 },
    tier: "flagship",
  },
  {
    id: "retro-wave", name: "Retro Wave",
    tagline: "Synthwave magenta, straight from 1986",
    description: "A neon synth grid, magenta accent, bold left taskbar, RGB accent-sync for the full battlestation.",
    category: "Retro", mood: "energetic", mode: "dark", accent_hex: "#FF2E88",
    gradient: ["#0D0221", "#7B2FF7"], wallpaper: { type: "scene", sceneId: "synth-grid" },
    sceneTweak: { speed: 1.3, density: 1.1 }, transparency: true,
    taskbar: { size: "large", alignment: "left", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats", "todo"], rgb: "accent-sync",
    tags: ["retro", "neon", "magenta", "energetic", "gaming", "scene"],
    quiz: { dark: 2, retro: 3, energetic: 2, gaming: 2, vivid: 2 },
    tier: "flagship", collection: "Neon '80s",
  },
  {
    id: "winter-snowfall", name: "Winter Snowfall",
    tagline: "Falling snow, frost-blue light",
    description: "An animated snowfall scene with an ice-blue accent and crisp light mode. Silent, cold, clean.",
    category: "Seasonal", mood: "calm", mode: "light", accent_hex: "#3B82C4",
    gradient: ["#F2F7FC", "#BCD4E8"], wallpaper: { type: "scene", sceneId: "winter-snow" },
    sceneTweak: { speed: 0.6, density: 1.2 }, transparency: true,
    taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"],
    tags: ["winter", "snow", "light", "calm", "scene"],
    quiz: { light: 2, cool: 2, calm: 2, motion: 1 },
    tier: "flagship", collection: "Nordic",
  },

  // ---- static photography --------------------------------------------------
  {
    id: "nordic-frost", name: "Nordic Frost",
    tagline: "Snowbound pines in ice-blue light",
    description: "Snow-forest photography, a frost accent, small left-aligned taskbar. Light mode that stays easy on the eyes all day.",
    category: "Seasonal", mood: "focused", mode: "light", accent_hex: "#4E8CBE",
    gradient: ["#F6FAFD", "#C9DCE8"], wallpaper: { type: "static", id: "snow-forest" },
    transparency: true, taskbar: { size: "small", alignment: "left", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"],
    tags: ["winter", "snow", "light", "focused", "clean"],
    quiz: { light: 3, cool: 2, focused: 2, minimal: 2, soft: 1 },
    tier: "flagship", collection: "Nordic",
  },
  {
    id: "alpine-summit", name: "Alpine Summit",
    tagline: "Crisp ridges above the treeline",
    description: "Alpine-ridge photography with a slate-blue accent. Dark, quiet, and built for deep focus sessions.",
    category: "Nature", mood: "focused", mode: "dark", accent_hex: "#5B7E9E",
    gradient: ["#101A24", "#2A3E52"], wallpaper: { type: "static", id: "alpine-ridge" },
    transparency: true, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["mountains", "alpine", "dark", "focused"],
    quiz: { dark: 2, nature: 3, focused: 2, cool: 1 },
    tier: "flagship",
  },
  {
    id: "forest-calm", name: "Forest Calm",
    tagline: "Olive mist over quiet trees",
    description: "Foggy-forest photography with a mossy olive accent. Grounded, green, and deliberately unhurried.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#8A9A5B",
    gradient: ["#101410", "#333D22"], wallpaper: { type: "static", id: "forest-mist" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["forest", "green", "calm", "nature"],
    quiz: { nature: 3, dark: 2, calm: 3, soft: 1 },
    tier: "flagship", collection: "Dark Forest",
  },
  {
    id: "ember-dusk", name: "Ember Dusk",
    tagline: "Copper light fading over the valley",
    description: "Golden-sunset photography, an amber accent, a centered taskbar. Warmth without the glare of a light theme.",
    category: "Cozy", mood: "cozy", mode: "dark", accent_hex: "#E0863B",
    gradient: ["#160D06", "#47260C"], wallpaper: { type: "static", id: "sunset-golden" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "note"],
    tags: ["sunset", "amber", "dark", "cozy"],
    quiz: { warm: 3, dark: 2, cozy: 2, soft: 1 },
    tier: "flagship",
  },
  {
    id: "golden-hour", name: "Golden Hour",
    tagline: "Honey light, soft shadows",
    description: "Golden-hour photography with a honey accent and a warm centered taskbar. The last twenty minutes of daylight, on your desktop.",
    category: "Cozy", mood: "cozy", mode: "dark", accent_hex: "#C9974E",
    gradient: ["#171008", "#4A3A1A"], wallpaper: { type: "static", id: "golden-hour" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "note"],
    tags: ["golden", "warm", "dark", "cozy"],
    quiz: { warm: 3, cozy: 3, dark: 1, soft: 2 },
    tier: "flagship",
  },
  {
    id: "lagoon", name: "Lagoon",
    tagline: "Turquoise shallows, all day",
    description: "Tropical-beach photography with a turquoise accent and light mode. Your monitor is now a vacation.",
    category: "Nature", mood: "calm", mode: "light", accent_hex: "#17A8A0",
    gradient: ["#EAFBF7", "#8FD8D2"], wallpaper: { type: "static", id: "tropical-beach" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "calendar"],
    tags: ["beach", "tropical", "light", "calm"],
    quiz: { light: 3, nature: 2, cool: 2, calm: 2 },
    tier: "flagship", collection: "Nordic",
  },
  {
    id: "marble-minimal", name: "Marble Minimal",
    tagline: "White marble, zero distraction",
    description: "Marble-white wallpaper, a slate accent, mono type, and nothing else competing for your attention. For people who ship.",
    category: "Minimal", mood: "focused", mode: "light", accent_hex: "#4A5568",
    gradient: ["#FAFAFC", "#D4D8DE"], wallpaper: { type: "static", id: "marble-white" },
    transparency: false, taskbar: { size: "small", alignment: "left" }, cursor: "black",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"], font: "Consolas",
    tags: ["marble", "minimal", "mono", "focused"],
    quiz: { light: 3, neutral: 3, minimal: 3, mono: 3, focused: 2 },
    tier: "flagship", collection: "Studio",
  },
  {
    id: "deep-space-ops", name: "Deep Space Ops",
    tagline: "Mission control, dark mode",
    description: "Starfield photography, an indigo accent, black cursors, mono type. Your PC is now mission control.",
    category: "Space", mood: "focused", mode: "dark", accent_hex: "#3D5AF1",
    gradient: ["#02030A", "#101B4D"], wallpaper: { type: "static", id: "starfield" },
    transparency: false, taskbar: { size: "small", alignment: "left" }, cursor: "black",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"], font: "Consolas",
    tags: ["space", "stars", "focused", "dark", "mono"],
    quiz: { dark: 3, space: 3, focused: 2, mono: 2, cool: 1 },
    tier: "flagship", collection: "Studio",
  },
  {
    id: "starry-horizon", name: "Starry Horizon",
    tagline: "Mountains under a full sky",
    description: "Starry-mountain photography with a deep indigo accent. Big sky, quiet thoughts.",
    category: "Space", mood: "calm", mode: "dark", accent_hex: "#4A6CF7",
    gradient: ["#030512", "#111B45"], wallpaper: { type: "static", id: "starry-mountain" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"],
    tags: ["stars", "mountains", "dark", "calm"],
    quiz: { space: 3, dark: 2, calm: 2, nature: 1 },
    tier: "flagship", collection: "Midnight",
  },
  {
    id: "neon-megacity", name: "Neon Megacity",
    tagline: "City lights that never sleep",
    description: "City-night photography, an electric-blue accent, a bold taskbar, RGB accent-sync. Pure late-night energy.",
    category: "Gaming", mood: "energetic", mode: "dark", accent_hex: "#3D8BFF",
    gradient: ["#0A0F1E", "#1E3A6E"], wallpaper: { type: "static", id: "city-night" },
    transparency: true, taskbar: { size: "large", alignment: "left", color_match: true }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "stats", "todo"], rgb: "accent-sync",
    tags: ["city", "neon", "night", "energetic", "gaming"],
    quiz: { dark: 3, city: 3, gaming: 2, energetic: 2, vivid: 1 },
    tier: "flagship",
  },
  {
    id: "glass-aurora", name: "Glass Aurora",
    tagline: "Violet glass, red light through it",
    description: "Abstract glass photography with a violet accent on near-black. Art that came from the wallpaper itself, not a color wheel.",
    category: "Abstract", mood: "calm", mode: "dark", accent_hex: "#7A4BD0",
    gradient: ["#0C0716", "#2E1B56"], wallpaper: { type: "static", id: "abstract-glass" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"],
    tags: ["abstract", "glass", "violet", "dark"],
    quiz: { dark: 3, abstract: 3, cool: 1, calm: 1 },
    tier: "flagship",
  },
  {
    id: "violet-haze", name: "Violet Haze",
    tagline: "Gradient violet, deep focus",
    description: "A violet gradient wallpaper, a matching accent, a translucent taskbar. Smooth, moody, quiet.",
    category: "Abstract", mood: "focused", mode: "dark", accent_hex: "#8B5CF6",
    gradient: ["#0C0716", "#3B2E8C"], wallpaper: { type: "static", id: "gradient-purple" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["violet", "gradient", "dark", "focused"],
    quiz: { dark: 3, abstract: 2, cool: 1, focused: 2 },
    tier: "flagship",
  },
  {
    id: "emerald-valley", name: "Emerald Valley",
    tagline: "Green hills after the rain",
    description: "Green-valley photography with a forest-green accent. Rich, organic, and easy to work in.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#7FA650",
    gradient: ["#0A140A", "#2A4018"], wallpaper: { type: "static", id: "green-valley" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["green", "valley", "dark", "nature"],
    quiz: { nature: 3, dark: 2, calm: 2, soft: 1 },
    tier: "flagship", collection: "Dark Forest",
  },
  {
    id: "misty-morning", name: "Misty Morning",
    tagline: "Lake fog, muted green light",
    description: "Misty-lake photography with a soft green accent. The desktop equivalent of a slow weekend.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#8A9A7A",
    gradient: ["#0E1410", "#2E3A2E"], wallpaper: { type: "static", id: "misty-lake" },
    transparency: true, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["lake", "mist", "dark", "calm"],
    quiz: { nature: 2, calm: 3, dark: 1, soft: 2 },
    tier: "flagship", collection: "Dark Forest",
  },
  {
    id: "waterfall-zen", name: "Waterfall Zen",
    tagline: "Falling water, steady focus",
    description: "Waterfall photography with a deep green accent. Motion that stays still enough to work next to.",
    category: "Nature", mood: "focused", mode: "dark", accent_hex: "#6B8A6B",
    gradient: ["#0C140C", "#2A3A2A"], wallpaper: { type: "static", id: "waterfall" },
    transparency: true, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["waterfall", "green", "dark", "focused"],
    quiz: { nature: 3, focused: 2, calm: 2, cool: 1 },
    tier: "flagship", collection: "Dark Forest",
  },
  {
    id: "sunlit-grove", name: "Sunlit Grove",
    tagline: "Light through the canopy",
    description: "Sunlit-forest photography with a deep green accent. Dark chrome, bright day, green light everywhere.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#5A9E6B",
    gradient: ["#0A140C", "#24401F"], wallpaper: { type: "static", id: "sunlit-forest" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["forest", "sunlight", "green", "dark"],
    quiz: { nature: 3, dark: 2, calm: 2, warm: 1 },
    tier: "flagship", collection: "Dark Forest",
  },
  {
    id: "cherry-morning", name: "Cherry Morning",
    tagline: "Blossoms in the dark",
    description: "Cherry-blossom photography with a soft pink accent on a dark desktop. Spring, after hours.",
    category: "Seasonal", mood: "calm", mode: "dark", accent_hex: "#E08AB0",
    gradient: ["#14080E", "#3A1626"], wallpaper: { type: "static", id: "cherry-blossoms" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "calendar"],
    tags: ["cherry", "blossom", "pink", "dark"],
    quiz: { dark: 2, warm: 2, cozy: 2, soft: 2, nature: 1 },
    tier: "flagship",
  },
  {
    id: "orbit-earth", name: "Orbit Earth",
    tagline: "The planet, from up here",
    description: "Earth-from-space photography with a calm blue accent. Perspective, installed.",
    category: "Space", mood: "calm", mode: "dark", accent_hex: "#3D7BD0",
    gradient: ["#060A14", "#16264A"], wallpaper: { type: "static", id: "earth-from-space" },
    transparency: true, taskbar: { size: "medium", alignment: "center", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["earth", "space", "dark", "calm"],
    quiz: { space: 3, dark: 2, cool: 2, calm: 2 },
    tier: "flagship", collection: "Midnight",
  },
  {
    id: "golden-savanna", name: "Golden Savanna",
    tagline: "Dry grass, bright morning",
    description: "Orange-flower photography with a honey accent and light mode. Warm without going dark about it.",
    category: "Warm", mood: "cozy", mode: "light", accent_hex: "#C08A38",
    gradient: ["#FDF9F0", "#EAD9B0"], wallpaper: { type: "static", id: "orange-flowers" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "note"],
    tags: ["orange", "flowers", "light", "warm"],
    quiz: { light: 3, warm: 3, cozy: 2, soft: 1 },
    tier: "flagship",
  },

  // ---- live video ----------------------------------------------------------
  {
    id: "aurora-night", name: "Aurora Night",
    tagline: "A living aurora over a dark horizon",
    description: "Live aurora video, an indigo accent, a glassy color-matched taskbar. Space calm at its best.",
    category: "Space", mood: "calm", mode: "dark", accent_hex: "#5B8BD6",
    gradient: ["#050816", "#1E2A5A"], wallpaper: { type: "live", id: "blue-aurora" },
    transparency: true, taskbar: { size: "medium", alignment: "center", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"],
    tags: ["space", "aurora", "dark", "calm", "live"],
    quiz: { dark: 3, space: 3, cool: 2, calm: 2, motion: 2 },
    tier: "flagship",
  },
  {
    id: "ember-lounge", name: "Ember Lounge",
    tagline: "Cozy amber glow for slow evenings",
    description: "Live embers, a warm amber accent, a soft-centered taskbar. Pour one out and settle in.",
    category: "Cozy", mood: "cozy", mode: "dark", accent_hex: "#E8862B",
    gradient: ["#140A05", "#4A1D08"], wallpaper: { type: "live", id: "amber-ember" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "note"],
    tags: ["warm", "cozy", "amber", "evening", "live"],
    quiz: { warm: 3, cozy: 3, dark: 2, calm: 1, motion: 2 },
    tier: "flagship",
  },
  {
    id: "coral-drift", name: "Coral Drift",
    tagline: "Warm currents under a coral sun",
    description: "Live coral flow, a warm coral accent, a translucent taskbar. Ocean energy, softened.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#FF6B57",
    gradient: ["#120807", "#5A1F14"], wallpaper: { type: "live", id: "coral-flow" },
    sceneTweak: { speed: 0.8, density: 1.0 }, transparency: true,
    taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["live", "coral", "ocean", "warm", "calm"],
    quiz: { warm: 3, nature: 2, calm: 2, cozy: 1, motion: 2 },
    tier: "flagship", collection: "Ocean",
  },
  {
    id: "emerald-tide", name: "Emerald Tide",
    tagline: "Green light through deep water",
    description: "Live emerald video, a forest-green accent, a centered taskbar. Rich, organic, calm.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#2E9E5B",
    gradient: ["#04120A", "#0E3B22"], wallpaper: { type: "live", id: "emerald-depth" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["emerald", "nature", "dark", "deep", "live"],
    quiz: { nature: 3, dark: 2, calm: 2, cool: 1, motion: 2 },
    tier: "flagship", collection: "Ocean",
  },
  {
    id: "teal-lagoon", name: "Teal Lagoon",
    tagline: "Slow waves, turquoise light",
    description: "Live teal waves, a lagoon accent, a color-matched taskbar. Cool water, warm vibes.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#2DD4BF",
    gradient: ["#041412", "#0C403A"], wallpaper: { type: "live", id: "teal-wave" },
    transparency: true, taskbar: { size: "medium", alignment: "center", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["lagoon", "teal", "dark", "calm", "live"],
    quiz: { nature: 2, cool: 3, calm: 3, motion: 2 },
    tier: "flagship", collection: "Ocean",
  },
  {
    id: "violet-bloom", name: "Violet Bloom",
    tagline: "A living violet garden",
    description: "Live violet video, a matching accent, a bold centered taskbar. Neon-soft, deeply colorful.",
    category: "Vibrant", mood: "energetic", mode: "dark", accent_hex: "#9B6CF0",
    gradient: ["#0A0817", "#2E2760"], wallpaper: { type: "live", id: "violet-bloom" },
    transparency: true, taskbar: { size: "large", alignment: "center", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["violet", "vibrant", "dark", "live"],
    quiz: { dark: 2, abstract: 2, bold: 2, energetic: 2, vivid: 2 },
    tier: "flagship",
  },
  {
    id: "smoke-noir", name: "Smoke Noir",
    tagline: "Black ink, silver edges",
    description: "Live ink swirl, a neutral accent, an opaque taskbar, mono type. Noir for the desktop.",
    category: "Minimal", mood: "calm", mode: "dark", accent_hex: "#8A8A9A",
    gradient: ["#050506", "#1C1C24"], wallpaper: { type: "live", id: "ink-swirl" },
    transparency: false, taskbar: { size: "small", alignment: "left" }, cursor: "black",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"], font: "Consolas",
    tags: ["ink", "noir", "dark", "monochrome", "live"],
    quiz: { dark: 3, neutral: 2, mono: 2, minimal: 2, calm: 1 },
    tier: "flagship", collection: "Studio",
  },
  {
    id: "bokeh-evening", name: "Bokeh Evening",
    tagline: "City lights through soft glass",
    description: "Live light bokeh, a warm gold accent, a centered taskbar. Night out, but make it calm.",
    category: "Cozy", mood: "cozy", mode: "dark", accent_hex: "#F0A03C",
    gradient: ["#120C04", "#3A2A0E"], wallpaper: { type: "live", id: "light-bokeh" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "note"],
    tags: ["bokeh", "city", "warm", "cozy", "live"],
    quiz: { city: 2, warm: 2, cozy: 2, dark: 2, motion: 1 },
    tier: "flagship",
  },
  {
    id: "arcade-rain", name: "Arcade Rain",
    tagline: "Digital rain in living green",
    description: "Live digital rain, a neon-green accent, a bold taskbar, RGB accent-sync. The Matrix, but make it your PC.",
    category: "Gaming", mood: "energetic", mode: "dark", accent_hex: "#39E675",
    gradient: ["#040D06", "#123A1E"], wallpaper: { type: "live", id: "digital-rain" },
    transparency: true, taskbar: { size: "large", alignment: "left", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats", "todo"], rgb: "accent-sync",
    tags: ["gaming", "rain", "green", "live", "energetic"],
    quiz: { gaming: 3, dark: 2, energetic: 2, abstract: 1, vivid: 2 },
    tier: "flagship", collection: "Neon '80s",
  },
  {
    id: "cyber-grid", name: "Cyber Grid",
    tagline: "Tunnel vision into the grid",
    description: "Live neon tunnel, an electric accent, a bold taskbar, RGB accent-sync. Plug into the machine.",
    category: "Gaming", mood: "energetic", mode: "dark", accent_hex: "#22D3EE",
    gradient: ["#020A12", "#0A3A52"], wallpaper: { type: "live", id: "neon-tunnel" },
    transparency: true, taskbar: { size: "large", alignment: "left", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"], rgb: "accent-sync",
    tags: ["cyber", "grid", "neon", "energetic", "gaming", "live"],
    quiz: { gaming: 3, dark: 2, cool: 2, energetic: 2, vivid: 2 },
    tier: "flagship", collection: "Neon '80s",
  },
  {
    id: "molten-gold", name: "Molten Gold",
    tagline: "Floating embers in gold dust",
    description: "Live gold particles, a brass accent, a slim centered taskbar. Minimal, warm, quietly luxurious.",
    category: "Warm", mood: "cozy", mode: "dark", accent_hex: "#D4A017",
    gradient: ["#0F0C05", "#3A2F0D"], wallpaper: { type: "live", id: "gold-particles" },
    transparency: false, taskbar: { size: "small", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["live", "gold", "particles", "minimal", "cozy"],
    quiz: { dark: 2, warm: 2, cozy: 3, minimal: 2, neutral: 1, motion: 2 },
    tier: "flagship",
  },
  {
    id: "pink-drift", name: "Pink Drift",
    tagline: "Rain in soft pink light",
    description: "Live pink rain, a rose accent, a centered taskbar. Dreamy, bright, alive.",
    category: "Vibrant", mood: "playful", mode: "light", accent_hex: "#D65E8E",
    gradient: ["#FDF5F8", "#F0C2D4"], wallpaper: { type: "live", id: "pink-rain" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "calendar"],
    tags: ["pink", "rain", "light", "playful", "live"],
    quiz: { light: 2, warm: 2, playful: 3, soft: 2, motion: 2 },
    tier: "flagship",
  },

  // -------------------------------------------------------------------------
  // A1.2 expansion — category × mood coverage + era collections (37 new)
  // -------------------------------------------------------------------------

  // ---- light mode (was nearly empty) ----
  {
    id: "solar-flare", name: "Solar Flare",
    tagline: "A warm gradient with the volume up",
    description: "Bright gradient-warm photography, an amber accent, light mode. Energetic without a single dark pixel.",
    category: "Warm", mood: "energetic", mode: "light", accent_hex: "#E6C078",
    gradient: ["#FDF6EC", "#F0D9B4"], wallpaper: { type: "static", id: "gradient-warm" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "todo"],
    tags: ["warm", "light", "energetic", "sunrise"],
    quiz: { light: 3, warm: 3, energetic: 2, bold: 1 },
    tier: "flagship",
  },
  {
    id: "high-tide", name: "High Tide",
    tagline: "Wave foam in warm sand light",
    description: "Beach-wave photography, a sand accent, light mode. The tide coming in, minus the salt.",
    category: "Nature", mood: "calm", mode: "light", accent_hex: "#AC948C",
    gradient: ["#FBF7F3", "#E8D8D0"], wallpaper: { type: "static", id: "beach-waves" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "calendar"],
    tags: ["beach", "waves", "light", "calm"],
    quiz: { light: 3, nature: 3, calm: 2, warm: 1 },
    tier: "flagship", collection: "Ocean",
  },
  {
    id: "coastal-morning", name: "Coastal Morning",
    tagline: "A pale beach under a pale sky",
    description: "Tropical-beach photography, a cream accent, light mode. Lighter than Lagoon, just as far away.",
    category: "Nature", mood: "calm", mode: "light", accent_hex: "#D4BCA4",
    gradient: ["#FDFAF5", "#EFE3D4"], wallpaper: { type: "static", id: "tropical-beach" },
    transparency: true, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock"],
    tags: ["beach", "light", "calm", "minimal"],
    quiz: { light: 3, nature: 2, calm: 2, soft: 2 },
    tier: "flagship", collection: "Ocean",
  },
  {
    id: "glass-district", name: "Glass District",
    tagline: "A bright skyline in slate glass",
    description: "Neon-city photography in bright light, a slate accent, bold taskbar. The city at noon, all chrome.",
    category: "City", mood: "energetic", mode: "light", accent_hex: "#888888",
    gradient: ["#F7F8FA", "#D9DDE3"], wallpaper: { type: "static", id: "neon-city2" },
    transparency: true, taskbar: { size: "large", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats", "todo"],
    tags: ["city", "light", "energetic", "chrome"],
    quiz: { light: 2, city: 3, energetic: 2, bold: 2, neutral: 1 },
    tier: "flagship",
  },
  {
    id: "blush-pop", name: "Blush Pop",
    tagline: "Pink abstract, fully awake",
    description: "Pink-abstract photography, a rose accent, light mode. Soft subject, confident chrome.",
    category: "Vibrant", mood: "playful", mode: "light", accent_hex: "#B088BE",
    gradient: ["#FDF7FB", "#F0DCE8"], wallpaper: { type: "static", id: "pink-abstract" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "calendar"],
    tags: ["pink", "abstract", "light", "playful"],
    quiz: { light: 2, warm: 2, playful: 3, soft: 2, bold: 1 },
    tier: "flagship",
  },
  {
    id: "studio-linen", name: "Studio Linen",
    tagline: "Marble-gray, shot in soft light",
    description: "Abstract-marble photography, a slate accent, mono type, light mode. A studio where the work leads.",
    category: "Minimal", mood: "focused", mode: "light", accent_hex: "#889098",
    gradient: ["#FAFAFC", "#DDE1E6"], wallpaper: { type: "static", id: "abstract-marble" },
    transparency: false, taskbar: { size: "small", alignment: "left" }, cursor: "black",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"], font: "Consolas",
    tags: ["marble", "studio", "light", "minimal", "mono"],
    quiz: { light: 3, neutral: 3, minimal: 3, mono: 2, focused: 2 },
    tier: "flagship", collection: "Studio",
  },
  {
    id: "ghost-particles", name: "Ghost Particles",
    tagline: "Live dust in a bright room",
    description: "Live light-particles video, a pale accent, light mode. Motion you can almost hear.",
    category: "Minimal", mood: "calm", mode: "light", accent_hex: "#7E8890",
    gradient: ["#FAFBFD", "#DDE2E6"], wallpaper: { type: "live", id: "light-particles" },
    transparency: true, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"],
    tags: ["live", "particles", "light", "minimal", "calm"],
    quiz: { light: 3, neutral: 2, calm: 2, minimal: 2, motion: 1 },
    tier: "flagship",
  },
  {
    id: "polar-lake", name: "Polar Lake",
    tagline: "Still water under a bright sky",
    description: "Mountain-lake photography, an ice-gray accent, light mode. Nordic calm for a bright day.",
    category: "Nature", mood: "focused", mode: "light", accent_hex: "#8E969E",
    gradient: ["#F9FBFD", "#DCE3E8"], wallpaper: { type: "static", id: "mountain-lake" },
    transparency: true, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["lake", "nordic", "light", "focused"],
    quiz: { light: 3, nature: 2, focused: 2, cool: 2, soft: 1 },
    tier: "flagship", collection: "Nordic",
  },
  {
    id: "paper-plane", name: "Paper Plane",
    tagline: "Abstract-minimal, no turbulence",
    description: "Abstract-minimal photography, a periwinkle accent, light mode. Clean surfaces for clean thinking.",
    category: "Minimal", mood: "focused", mode: "light", accent_hex: "#8CB4CC",
    gradient: ["#F9FBFD", "#DCE6EE"], wallpaper: { type: "static", id: "abstract-minimal" },
    transparency: true, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["minimal", "abstract", "light", "focused"],
    quiz: { light: 3, minimal: 3, focused: 2, cool: 1 },
    tier: "flagship", collection: "Studio",
  },
  {
    id: "autumn-hearth", name: "Autumn Hearth",
    tagline: "Leaves in bright, warm light",
    description: "Autumn-leaves photography, a soft-gray accent, light mode. The season without the evening.",
    category: "Seasonal", mood: "cozy", mode: "light", accent_hex: "#A0A0A0",
    gradient: ["#FBF8F2", "#EAE0D0"], wallpaper: { type: "static", id: "autumn-leaves" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "note"],
    tags: ["autumn", "light", "cozy", "warm"],
    quiz: { light: 2, warm: 3, cozy: 2, soft: 2 },
    tier: "flagship",
  },

  // ---- dark cozy + warm fills ----
  {
    id: "sunrise-commute", name: "Sunrise Commute",
    tagline: "A honey sky, caught on camera",
    description: "Sunrise photography, a honey accent, dark mode. The commute that makes the morning worth it.",
    category: "Warm", mood: "energetic", mode: "dark", accent_hex: "#908868",
    gradient: ["#171008", "#4A3A1A"], wallpaper: { type: "static", id: "sunrise-person" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "todo"],
    tags: ["sunrise", "warm", "dark", "energetic"],
    quiz: { warm: 3, dark: 2, energetic: 2, soft: 1 },
    tier: "flagship",
  },
  {
    id: "mossy-vale", name: "Mossy Vale",
    tagline: "Moss-green fog, cozy as a blanket",
    description: "Foggy-valley photography, a mossy accent, dark mode. Green calm that wraps around you.",
    category: "Nature", mood: "cozy", mode: "dark", accent_hex: "#6C7444",
    gradient: ["#0E1208", "#2E3A1E"], wallpaper: { type: "static", id: "foggy-valley" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "note"],
    tags: ["moss", "fog", "dark", "cozy"],
    quiz: { nature: 3, dark: 2, cozy: 3, soft: 1 },
    tier: "flagship", collection: "Dark Forest",
  },
  {
    id: "midnight-cabin", name: "Midnight Cabin",
    tagline: "Storm clouds and a fire inside",
    description: "Dark-cloud photography, a deep-blue accent, dark mode. The weather outside, the warmth inside.",
    category: "Cozy", mood: "cozy", mode: "dark", accent_hex: "#37575F",
    gradient: ["#0A0F14", "#1E3038"], wallpaper: { type: "static", id: "dark-clouds" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "note"],
    tags: ["storm", "dark", "cozy", "cabin"],
    quiz: { dark: 3, cozy: 3, calm: 2, cool: 1 },
    tier: "flagship", collection: "Midnight",
  },
  {
    id: "smoke-and-mirrors", name: "Smoke & Mirrors",
    tagline: "Living smoke in teal light",
    description: "Live colored smoke, a teal accent, dark mode. Calm that keeps moving, softly.",
    category: "Cozy", mood: "cozy", mode: "dark", accent_hex: "#5494AC",
    gradient: ["#0A1014", "#1E3440"], wallpaper: { type: "live", id: "smoke-colors" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "note"],
    tags: ["live", "smoke", "teal", "cozy"],
    quiz: { dark: 2, cool: 2, cozy: 3, calm: 2, motion: 1 },
    tier: "flagship",
  },
  {
    id: "ember-marsh", name: "Ember Marsh",
    tagline: "Golden-hour browns, low and warm",
    description: "Golden-hour photography, a warm-brown accent, dark mode. Dusk that feels like a blanket.",
    category: "Seasonal", mood: "cozy", mode: "dark", accent_hex: "#544C34",
    gradient: ["#141008", "#3A3018"], wallpaper: { type: "static", id: "golden-hour" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "note"],
    tags: ["golden", "brown", "dark", "cozy"],
    quiz: { warm: 3, cozy: 3, dark: 2, soft: 1 },
    tier: "flagship",
  },

  // ---- seasonal fills ----
  {
    id: "festival-lights", name: "Festival Lights",
    tagline: "Holiday glow on a living grid",
    description: "The Holiday Lights scene, a gold accent, bold taskbar. The most energetic time of year, on demand.",
    category: "Seasonal", mood: "energetic", mode: "dark", accent_hex: "#FBBF24",
    gradient: ["#140D04", "#3A2A0E"], wallpaper: { type: "scene", sceneId: "holiday-lights" },
    sceneTweak: { speed: 0.9, density: 1.2 }, transparency: true,
    taskbar: { size: "large", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats", "todo"],
    tags: ["scene", "holiday", "lights", "energetic"],
    quiz: { warm: 3, energetic: 3, playful: 2, dark: 2, motion: 2 },
    tier: "flagship",
  },
  {
    id: "sparkler-night", name: "Sparkler Night",
    tagline: "Silver sparks against the dark",
    description: "Live silver-sparkle video, a pale accent, dark mode. Small celebrations, all year.",
    category: "Seasonal", mood: "playful", mode: "dark", accent_hex: "#A0B0B8",
    gradient: ["#0A0C10", "#26303A"], wallpaper: { type: "live", id: "silver-sparkle" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "calendar"],
    tags: ["live", "sparkle", "silver", "playful"],
    quiz: { dark: 2, neutral: 2, playful: 3, cozy: 1, motion: 2 },
    tier: "flagship",
  },

  // ---- space fills ----
  {
    id: "galactic-drift", name: "Galactic Drift",
    tagline: "A slow swirl in muted violet",
    description: "Galaxy-swirl photography, a brown-violet accent, dark mode. Vast and quiet, like space should be.",
    category: "Space", mood: "calm", mode: "dark", accent_hex: "#645C54",
    gradient: ["#0A0810", "#24202A"], wallpaper: { type: "static", id: "galaxy-swirl" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["galaxy", "space", "dark", "calm"],
    quiz: { space: 3, dark: 2, calm: 2, neutral: 1 },
    tier: "flagship",
  },
  {
    id: "solar-wind", name: "Solar Wind",
    tagline: "Aurora-earth, seen from the edge",
    description: "Aurora-earth photography, a cool gray accent, dark mode. The planet, humming at the edge of night.",
    category: "Space", mood: "energetic", mode: "dark", accent_hex: "#707A80",
    gradient: ["#050810", "#1E2830"], wallpaper: { type: "static", id: "aurora-earth" },
    transparency: true, taskbar: { size: "large", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["earth", "aurora", "space", "energetic"],
    quiz: { space: 3, dark: 2, energetic: 2, cool: 1 },
    tier: "flagship",
  },
  {
    id: "lunar-surface", name: "Lunar Surface",
    tagline: "Crater field, dead quiet",
    description: "Moon-crater photography, a dark-green accent, dark mode. The quietest place in the solar system.",
    category: "Space", mood: "focused", mode: "dark", accent_hex: "#344434",
    gradient: ["#050806", "#101C14"], wallpaper: { type: "static", id: "moon-craters" },
    transparency: true, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["moon", "space", "dark", "focused"],
    quiz: { space: 3, dark: 3, focused: 2, nature: 1 },
    tier: "flagship",
  },
  {
    id: "deep-nebula", name: "Deep Nebula",
    tagline: "A purple cloud at arm's length",
    description: "Nebula-deep photography, a muted violet accent, dark mode. The cosmos, reduced to a desktop.",
    category: "Space", mood: "calm", mode: "dark", accent_hex: "#706070",
    gradient: ["#0A0810", "#2A2030"], wallpaper: { type: "static", id: "nebula-deep" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"],
    tags: ["nebula", "space", "dark", "calm"],
    quiz: { space: 3, dark: 2, cool: 2, calm: 2 },
    tier: "flagship",
  },

  // ---- Neon '80s collection ----
  {
    id: "sunset-drive", name: "Sunset Drive",
    tagline: "A grid on fire, radio up",
    description: "The Retro Sunset scene, magenta accent, bold taskbar. Driving into the synthwave horizon.",
    category: "Retro", mood: "energetic", mode: "dark", accent_hex: "#FF2E88",
    gradient: ["#1A0E2E", "#7B2FF7"], wallpaper: { type: "scene", sceneId: "retro-sunset" },
    sceneTweak: { speed: 1.0, density: 1.0 }, transparency: true,
    taskbar: { size: "large", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "todo"], rgb: "accent-sync",
    tags: ["scene", "retro", "magenta", "energetic"],
    quiz: { dark: 2, retro: 3, energetic: 2, warm: 2, vivid: 2 },
    tier: "flagship", collection: "Neon '80s",
  },
  {
    id: "synth-tides", name: "Synth Tides",
    tagline: "Purple geometry, softer edges",
    description: "The Synth Grid scene at a slower pulse, violet accent, centered taskbar. Retro, but relaxed.",
    category: "Retro", mood: "playful", mode: "dark", accent_hex: "#7B2FF7",
    gradient: ["#0D0221", "#4C1D95"], wallpaper: { type: "scene", sceneId: "synth-grid" },
    sceneTweak: { speed: 0.8, density: 0.9 }, transparency: true,
    taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["scene", "retro", "violet", "playful"],
    quiz: { dark: 2, retro: 3, playful: 2, cool: 2, motion: 1 },
    tier: "flagship", collection: "Neon '80s",
  },
  {
    id: "magenta-pulse", name: "Magenta Pulse",
    tagline: "A live pulse in electric blue",
    description: "Live magenta-pulse video, an electric-blue accent, bold taskbar. Retro-futurist and always on.",
    category: "Retro", mood: "energetic", mode: "dark", accent_hex: "#3484D4",
    gradient: ["#080A16", "#1E3A66"], wallpaper: { type: "live", id: "magenta-pulse" },
    transparency: true, taskbar: { size: "large", alignment: "left", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats", "todo"],
    tags: ["live", "pulse", "retro", "energetic"],
    quiz: { dark: 2, retro: 3, cool: 2, energetic: 2, motion: 2 },
    tier: "flagship", collection: "Neon '80s",
  },

  // ---- Dark Forest collection (continued) ----
  {
    id: "emerald-canopy", name: "Emerald Canopy",
    tagline: "Sun-forest green, low light",
    description: "Sunforest photography, a deep gray-green accent, dark mode. The canopy, seen from the floor.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#5F6F6F",
    gradient: ["#0A100E", "#223030"], wallpaper: { type: "static", id: "sunforest" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["forest", "canopy", "dark", "calm"],
    quiz: { nature: 3, dark: 2, calm: 2, cool: 1 },
    tier: "flagship", collection: "Dark Forest",
  },
  {
    id: "fernglen", name: "Fernglen",
    tagline: "Bamboo shade in deep green",
    description: "Bamboo-forest photography, a pine accent, dark mode. The forest, holding its breath.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#3F6757",
    gradient: ["#080F0C", "#1E3628"], wallpaper: { type: "static", id: "bamboo-forest" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["bamboo", "forest", "dark", "calm"],
    quiz: { nature: 3, dark: 2, calm: 3, cool: 1 },
    tier: "flagship", collection: "Dark Forest",
  },
  {
    id: "canyon-fern", name: "Canyon Fern",
    tagline: "Green hills in olive dark",
    description: "Green-hills photography, an olive accent, dark mode. Grounded, focused, alive.",
    category: "Nature", mood: "focused", mode: "dark", accent_hex: "#576737",
    gradient: ["#0A0F06", "#22301A"], wallpaper: { type: "static", id: "green-hills" },
    transparency: true, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["hills", "green", "dark", "focused"],
    quiz: { nature: 3, dark: 2, focused: 2, calm: 1 },
    tier: "flagship", collection: "Dark Forest",
  },
  {
    id: "river-grove", name: "River Grove",
    tagline: "Lake-green light, slow water",
    description: "Lake-reflection photography, a dark olive accent, dark mode. Water that barely moves.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#445410",
    gradient: ["#0A0F04", "#202E10"], wallpaper: { type: "static", id: "lake-reflection" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["lake", "grove", "dark", "calm"],
    quiz: { nature: 3, dark: 2, calm: 2, soft: 1 },
    tier: "flagship", collection: "Dark Forest",
  },

  // ---- Ocean collection (continued) ----
  {
    id: "tidal-current", name: "Tidal Current",
    tagline: "Bright waves in a dark room",
    description: "Ocean-wave photography, a pale-blue accent, dark mode. The current, at full volume.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#CCDCE4",
    gradient: ["#0A1014", "#22323C"], wallpaper: { type: "static", id: "ocean-waves" },
    transparency: true, taskbar: { size: "medium", alignment: "center", color_match: true }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["ocean", "waves", "dark", "calm"],
    quiz: { nature: 3, dark: 2, cool: 2, calm: 2 },
    tier: "flagship", collection: "Ocean",
  },
  {
    id: "siren-cove", name: "Siren Cove",
    tagline: "Storm water, dim and deep",
    description: "Storm-cloud photography, a slate-blue accent, dark mode. The sea before the weather turns.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#506878",
    gradient: ["#0A1014", "#22303A"], wallpaper: { type: "static", id: "storm-clouds" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["storm", "ocean", "dark", "calm"],
    quiz: { nature: 2, dark: 3, calm: 2, cool: 2 },
    tier: "flagship", collection: "Ocean",
  },
  {
    id: "kelp-bed", name: "Kelp Bed",
    tagline: "Jade water, current slow",
    description: "Live jade-swirl video, a deep-green accent, dark mode. The reef, breathing.",
    category: "Nature", mood: "calm", mode: "dark", accent_hex: "#2C6C64",
    gradient: ["#04120E", "#0E3B30"], wallpaper: { type: "live", id: "jade-swirl" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "calendar"],
    tags: ["live", "jade", "ocean", "calm"],
    quiz: { nature: 3, dark: 2, cool: 2, calm: 3, motion: 1 },
    tier: "flagship", collection: "Ocean",
  },

  // ---- Midnight collection (continued) ----
  {
    id: "midnight-express", name: "Midnight Express",
    tagline: "A skyline at quarter to three",
    description: "Skyline-dark photography, a slate-blue accent, dark mode. The city, after everyone left.",
    category: "City", mood: "calm", mode: "dark", accent_hex: "#3C4C5C",
    gradient: ["#0A0E14", "#1E2A3A"], wallpaper: { type: "static", id: "skyline-dark" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["skyline", "city", "dark", "calm"],
    quiz: { dark: 3, city: 3, calm: 2, cool: 1 },
    tier: "flagship", collection: "Midnight",
  },
  {
    id: "after-midnight", name: "After Midnight",
    tagline: "A wave that never lands",
    description: "Live obsidian-wave video, a muted violet accent, dark mode. The 3 a.m. channel.",
    category: "Abstract", mood: "calm", mode: "dark", accent_hex: "#6F6580",
    gradient: ["#08070E", "#242032"], wallpaper: { type: "live", id: "obsidian-wave" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["live", "obsidian", "dark", "calm"],
    quiz: { dark: 3, abstract: 2, calm: 2, cool: 2, motion: 1 },
    tier: "flagship", collection: "Midnight",
  },
  {
    id: "starlight-opera", name: "Starlight Opera",
    tagline: "Dark mountains under blue stars",
    description: "Dark-mountain photography, a deep-blue accent, dark mode. The overture to a clear night.",
    category: "Space", mood: "calm", mode: "dark", accent_hex: "#476B9B",
    gradient: ["#050A12", "#16263E"], wallpaper: { type: "static", id: "dark-mountains" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"],
    tags: ["mountains", "stars", "dark", "calm"],
    quiz: { space: 3, dark: 2, calm: 2, nature: 1 },
    tier: "flagship", collection: "Midnight",
  },
  {
    id: "raven-feather", name: "Raven Feather",
    tagline: "Ink in motion, slate quiet",
    description: "Live ink-drop video, a graphite accent, dark mode. Noir, without the plot.",
    category: "Minimal", mood: "calm", mode: "dark", accent_hex: "#747468",
    gradient: ["#080807", "#222220"], wallpaper: { type: "live", id: "ink-drop" },
    transparency: false, taskbar: { size: "small", alignment: "left" }, cursor: "black",
    lock_screen: { mode: "spotlight" }, widgets: ["clock"], font: "Consolas",
    tags: ["live", "ink", "dark", "minimal", "mono"],
    quiz: { dark: 3, neutral: 2, mono: 2, minimal: 3, calm: 1 },
    tier: "flagship", collection: "Midnight",
  },

  // ---- final gap fills ----
  {
    id: "neon-circuit", name: "Neon Circuit",
    tagline: "Black glass, one bright line",
    description: "Neon-lines photography, a cool-gray accent, dark mode. A single circuit, cut and glowing.",
    category: "Gaming", mood: "focused", mode: "dark", accent_hex: "#606060",
    gradient: ["#070707", "#1E1E1E"], wallpaper: { type: "static", id: "neon-lines" },
    transparency: false, taskbar: { size: "small", alignment: "left" }, cursor: "aero",
    lock_screen: { mode: "spotlight" }, widgets: ["clock", "stats"],
    tags: ["neon", "circuit", "dark", "focused"],
    quiz: { dark: 3, gaming: 2, focused: 3, neutral: 1 },
    tier: "flagship",
  },
  {
    id: "copper-forge", name: "Copper Forge",
    tagline: "Warm glow off the anvil",
    description: "Live copper-glow video, a dusky violet accent, dark mode. The forge, banked for the night.",
    category: "Warm", mood: "cozy", mode: "dark", accent_hex: "#5F5767",
    gradient: ["#0D0A12", "#2A2230"], wallpaper: { type: "live", id: "copper-glow" },
    transparency: true, taskbar: { size: "medium", alignment: "center" }, cursor: "aero",
    lock_screen: { mode: "image" }, widgets: ["clock", "note"],
    tags: ["live", "copper", "warm", "cozy"],
    quiz: { warm: 3, dark: 2, cozy: 3, calm: 1, motion: 1 },
    tier: "flagship",
  },
];

// ---------------------------------------------------------------------------
// S5.4 — curated sound schemes per flagship (K7). Assigned by design intent,
// not at random:
//   • Studio collection  → Windows Default under its canonical GUID (the
//     back-to-stock look; sounds.rs aliases it to ".Default" on machines that
//     store the default scheme under the plain name).
//   • focused mood / Nordic collection → No Sounds (".None") — silence is the
//     design opinion for a focus workspace and Scandinavian quiet.
//   • everything else   → Windows Default (".Default").
// Every guid is a real scheme present on stock Win10/11 (sound_schemes.ts).
// ---------------------------------------------------------------------------
import { SOUND_SCHEME_CANONICAL, SOUND_SCHEME_DEFAULT, SOUND_SCHEME_NONE } from "./sound_schemes";

for (const s of HERO_STYLES) {
  if (s.collection === "Studio") {
    s.sound_scheme = { ...SOUND_SCHEME_CANONICAL };
  } else if (s.mood === "focused" || s.collection === "Nordic") {
    s.sound_scheme = { ...SOUND_SCHEME_NONE };
  } else {
    s.sound_scheme = { ...SOUND_SCHEME_DEFAULT };
  }
}

export const HERO_BY_ID = new Map(HERO_STYLES.map((s) => [s.id, s]));

/** Curated era/collection sets (A1.2) — used by the studio collections filter. */
export const STYLE_COLLECTIONS = [
  "Studio", "Nordic", "Neon '80s", "Dark Forest", "Ocean", "Midnight",
] as const;
